package com.example.djilib.dji.djierror;


import dji.common.error.DJIMissionError;

public enum WayPointError {

    HOTPOINT_ALTITUDE_TOO_LOW(DJIMissionError. HOTPOINT_ALTITUDE_TOO_LOW.getErrorCode(),"飞机高度太低，无法执行热点任务。"),
    TARGET_IS_TOO_FAR_AWAY(DJIMissionError. TARGET_IS_TOO_FAR_AWAY.getErrorCode(),"目标太远，飞机需要继续测量距离。"),
    OBSTACLE_ENCOUNTERED_WHILE_SURROUNDING(DJIMissionError. OBSTACLE_ENCOUNTERED_WHILE_SURROUNDING.getErrorCode(),"周围遇到障碍物，当前任务暂停。"),
    OBSTACLE_ENCOUNTERED_WHILE_ESTIMATING(DJIMissionError. OBSTACLE_ENCOUNTERED_WHILE_ESTIMATING.getErrorCode(),"预估时遇到障碍，当前任务退出。"),
    LOST_CONNECTION_WITH_REMOTE_CONTROLLER(DJIMissionError. LOST_CONNECTION_WITH_REMOTE_CONTROLLER.getErrorCode(),"与遥控器的连接断开。"),
    CONTROL_FAILED(DJIMissionError. CONTROL_FAILED.getErrorCode(),"智能热点任务执行失败。"),
    ALTITUDE_LIMIT(DJIMissionError. RADIUS_LIMIT.getErrorCode(),"飞机到达了高度极限。请在高度限制内操作飞机。"),
    RADIUS_LIMIT(DJIMissionError. RADIUS_LIMIT.getErrorCode(),"飞机到达了距离极限。请在距离限制内操作飞机。"),
    EXIT_BY_USER_BUTTON(DJIMissionError. EXIT_BY_USER_BUTTON.getErrorCode(),"按用户按钮退出当前任务。"),
    ESTIMATE_RESULT_INVALID(DJIMissionError. ESTIMATE_RESULT_INVALID.getErrorCode(),"无法估计主题位置。"),

    ESTIMATE_TIMEOUT(DJIMissionError. ESTIMATE_TIMEOUT.getErrorCode(),"预估超时，任务退出。"),
    WATCH_TARGET_FAILED(DJIMissionError. WATCH_TARGET_FAILED.getErrorCode(),"云台角度偏转到达极限，请重试"),
    HOT_POINT_INVALID(DJIMissionError. HOT_POINT_INVALID.getErrorCode(),"兴趣点参数不符合要求"),

    GPS_ABNORMAL(DJIMissionError. GPS_ABNORMAL.getErrorCode(),"GPS信号弱。请在开放区域重试。"),

    TARGET_SIZE_CHANGED(DJIMissionError. TARGET_SIZE_CHANGED.getErrorCode(),"FTarget size changed, please try again. If the error persists, restart the aircraft."),
    TARGET_TOO_CLOSE(DJIMissionError. TARGET_TOO_CLOSE.getErrorCode(),"Frame subject too close."),
    REPROJECTION_FAILED_WHILE_EXECUTING(DJIMissionError. REPROJECTION_FAILED_WHILE_EXECUTING.getErrorCode(),"Failed to estimate, please try again"),
    LOST_TARGET_WHILE_EXECUTING(DJIMissionError. LOST_TARGET_WHILE_EXECUTING.getErrorCode(),"Tracking subject lost while executing."),

    MULTI_MODE_DISABLED(DJIMissionError. MULTI_MODE_DISABLED.getErrorCode(),"当禁用多模式时，任务无法启动。"),
    LOST_TARGET_WHILE_WATCHING(DJIMissionError. LOST_TARGET_WHILE_WATCHING.getErrorCode(),"跟踪对象在观看时丢失。"),
    INSUFFICIENT_FEATURES_IN_TARGET_AREA(DJIMissionError. INSUFFICIENT_FEATURES_IN_TARGET_AREA.getErrorCode(),"帧选择主体纹理不明显。"),
    TARGET_AREA_IS_TOO_SMALL(DJIMissionError. TARGET_AREA_IS_TOO_SMALL.getErrorCode(),"帧选择主题太小。"),
    SYSTEM_ABNORMAL(DJIMissionError. SYSTEM_ABNORMAL.getErrorCode(),"系统错误，请重试。如果错误继续，重启飞机。"),
    WAYPOINT_GET_INTERRUPTION_FAILURE_WITHOUT_REACHING_FIRST_WAYPOINT(DJIMissionError. WAYPOINT_GET_INTERRUPTION_FAILURE_WITHOUT_REACHING_FIRST_WAYPOINT.getErrorCode(),"航路点任务中断不可用，因为飞机在上一次任务中没有到达第一个航路点。"),
    WAYPOINT_GET_INTERRUPTION_FAILURE_FOR_COMPLETE_MISSION(DJIMissionError. WAYPOINT_GET_INTERRUPTION_FAILURE_FOR_COMPLETE_MISSION.getErrorCode(),"完成任务的航路点中断故障。"),
    INVALID_INTERVAL_SHOOT_PARAM(DJIMissionError. INVALID_INTERVAL_SHOOT_PARAM.getErrorCode(),"时间间隔或距离间隔无效。"),
    TAKE_OFF_FAILURE_CAUSED_BY_ATTITUDE(DJIMissionError. TAKE_OFF_FAILURE_CAUSED_BY_ATTITUDE.getErrorCode(),"由于飞机姿态不当，飞机无法起飞。"),
    INVALID_DATA_SIZE(DJIMissionError. INVALID_DATA_SIZE.getErrorCode(),"航路点数据大小无效。"),
    INDEX_OUT_OF_RANGE(DJIMissionError. INDEX_OUT_OF_RANGE.getErrorCode(),"航路点索引超出范围。"),
    INDICES_ARE_DISCONTINUOUS(DJIMissionError. INDICES_ARE_DISCONTINUOUS.getErrorCode(),"航路点索引是不连续的。"),
    ROTATE_AIRCRAFT_ACTION_NOT_VALID(DJIMissionError. ROTATE_AIRCRAFT_ACTION_NOT_VALID.getErrorCode(),"提供的航路点飞机偏转角度无效。"),
    ROTATE_GIMBAL_ACTION_NOT_VALID(DJIMissionError. ROTATE_GIMBAL_ACTION_NOT_VALID.getErrorCode(),"提供的航路点云台偏转角度无效。"),
    STAY_ACTION_NOT_VALID(DJIMissionError. STAY_ACTION_NOT_VALID.getErrorCode(),"提供的航路点停留动作参数无效。"),
    SHOOT_PHOTO_NOT_VALID(DJIMissionError. SHOOT_PHOTO_NOT_VALID.getErrorCode(),"提供的航路点拍摄照片距离无效"),
    WAYPOINT_SPEED_NOT_VALID(DJIMissionError. WAYPOINT_SPEED_NOT_VALID.getErrorCode(),"航点提供的速度无效"),
    GIMBAL_PITCH_NOT_VALID(DJIMissionError. GIMBAL_PITCH_NOT_VALID.getErrorCode(),"航点提供的云台角度"),
    CORNER_RADIUS_NOT_VALID(DJIMissionError. CORNER_RADIUS_NOT_VALID.getErrorCode(),"航点提供的转角半径无效"),
    ACTION_TIMEOUT_NOT_VALID(DJIMissionError. ACTION_TIMEOUT_NOT_VALID.getErrorCode(),"航点提供的操作超时无效"),
    ACTION_REPEAT_TIME_NOT_VALID(DJIMissionError. ACTION_REPEAT_TIME_NOT_VALID.getErrorCode(),"航点的重复时间无效。"),
    HEADING_NOT_VALID(DJIMissionError. HEADING_NOT_VALID.getErrorCode(),"航点航向无效。"),
    ALTITUDE_NOT_VALID(DJIMissionError. ALTITUDE_NOT_VALID.getErrorCode(),"航点高度无效。"),
    WAYPOINT_COORDINATE_NOT_VALID(DJIMissionError. WAYPOINT_COORDINATE_NOT_VALID.getErrorCode(),"航点位置信息无效。"),
    WAYPOINT_LIST_SIZE_NOT_VALID(DJIMissionError. WAYPOINT_LIST_SIZE_NOT_VALID.getErrorCode(),"航点列表大小无效。"),
    WAYPOINT_COUNT_NOT_VALID(DJIMissionError. WAYPOINT_COUNT_NOT_VALID.getErrorCode(),"航点计数无效。"),
    REPEAT_TIME_NOT_VALID(DJIMissionError. REPEAT_TIME_NOT_VALID.getErrorCode(),"提供的重复时间值无效。"),
    AUTO_FLIGHT_SPEED_NOT_VALID(DJIMissionError. AUTO_FLIGHT_SPEED_NOT_VALID.getErrorCode(),"自动飞行速度无效。"),
    MAX_FLIGHT_SPEED_NOT_VALID(DJIMissionError. MAX_FLIGHT_SPEED_NOT_VALID.getErrorCode(),"最大飞行速度无效。"),
    COMMON_STATE_ERROR(DJIMissionError. COMMON_STATE_ERROR.getErrorCode(),"当前状态下不支持该命令。"),
    MISSION_NOT_STARTED(DJIMissionError. MISSION_NOT_STARTED.getErrorCode(),"任务尚未开始"),
    REACH_ALTITUDE_LOWER_BOUND(DJIMissionError. REACH_ALTITUDE_LOWER_BOUND.getErrorCode(),"飞机到达最低高度"),
    TRACKING_OBSTACLE_DETECTED(DJIMissionError. TRACKING_OBSTACLE_DETECTED.getErrorCode(),"遇到障碍"),
    TRACKING_GIMBAL_PITCH_TOO_LOW(DJIMissionError. TRACKING_GIMBAL_PITCH_TOO_LOW.getErrorCode(),"云台角度太低"),
    TRACKING_PAUSED_BY_USER(DJIMissionError. TRACKING_PAUSED_BY_USER.getErrorCode(),"任务被用户暂停"),
    TRACKING_TARGET_LOW_CONFIDENCE(DJIMissionError. TRACKING_TARGET_LOW_CONFIDENCE.getErrorCode(),"无法确定跟踪对象"),
    TRACKING_TARGET_SHAKING(DJIMissionError. TRACKING_TARGET_SHAKING.getErrorCode(),"跟踪目标震动太大"),
    TRACKING_TARGET_TOO_HIGH(DJIMissionError. TRACKING_TARGET_TOO_HIGH.getErrorCode(),"跟踪目标太高"),
    TRACKING_TARGET_TOO_FAR(DJIMissionError. TRACKING_TARGET_TOO_FAR.getErrorCode(),"跟踪目标离飞机太远。"),
    TRACKING_TARGET_TOO_CLOSE(DJIMissionError. TRACKING_TARGET_TOO_CLOSE.getErrorCode(),"跟踪目标离飞机太近。"),
    TRACKING_TARGET_NOT_ENOUGH_FEATURES(DJIMissionError. TRACKING_TARGET_NOT_ENOUGH_FEATURES.getErrorCode(),"跟踪目标没有足够的功能来锁定。"),
    TRACKING_RECT_TOO_LARGE(DJIMissionError. TRACKING_RECT_TOO_LARGE.getErrorCode(),"跟踪矩形太大。"),
    TRACKING_RECT_TOO_SMALL(DJIMissionError. TRACKING_RECT_TOO_SMALL.getErrorCode(),"跟踪矩形太小。"),
    FEATURE_POINT_CANNOT_MATCH(DJIMissionError. FEATURE_POINT_CANNOT_MATCH.getErrorCode(),"两个视觉传感器找到的特征点不匹配。"),
    VISION_DATA_ABNORMAL(DJIMissionError. VISION_DATA_ABNORMAL.getErrorCode(),"来自视觉系统的数据异常。"),
    VISION_SENSOR_UNDEREXPOSED(DJIMissionError. VISION_SENSOR_UNDEREXPOSED.getErrorCode(),"视觉传感器曝光不足。"),
    VISION_SENSOR_OVEREXPOSED(DJIMissionError. VISION_SENSOR_OVEREXPOSED.getErrorCode(),"视觉传感器曝光过度。"),
    VISION_SYSTEM_NEEDS_CALIBRATION(DJIMissionError. VISION_SYSTEM_NEEDS_CALIBRATION.getErrorCode(),"视觉系统需要校准。"),
    STOPPED_BY_USER(DJIMissionError. STOPPED_BY_USER.getErrorCode(),"已被用户停止。"),
    CANNOT_BYPASS_OBSTACLE(DJIMissionError. CANNOT_BYPASS_OBSTACLE.getErrorCode(),"飞机无法绕过障碍物。"),
    VISION_SYSTEM_ERROR(DJIMissionError. VISION_SYSTEM_ERROR.getErrorCode(),"视觉系统错误。"),
    VISION_SYSTEM_NOT_AUTHORIZED(DJIMissionError. VISION_SYSTEM_NOT_AUTHORIZED.getErrorCode(),"视觉系统未经授权。"),
    VIDEO_FRAME_RATE_TOO_LOW(DJIMissionError. VIDEO_FRAME_RATE_TOO_LOW.getErrorCode(),"实时视频源的帧速率太低。"),
    NO_VIDEO_FEED(DJIMissionError. NO_VIDEO_FEED.getErrorCode(),"没有为ActiveTrack任务捕获实时视频源。"),
    TRACKING_TARGET_LOST(DJIMissionError. TRACKING_TARGET_LOST.getErrorCode(),"跟踪目标丢失。"),
    MISSION_RESUME_FAILED(DJIMissionError. MISSION_RESUME_FAILED.getErrorCode(),"任务恢复失败。"),
    MISSION_PARAMETERS_INVALID(DJIMissionError. MISSION_PARAMETERS_INVALID.getErrorCode(),"任务参数无效。"),
    TOO_CLOSE_TO_HOME_POINT(DJIMissionError. TOO_CLOSE_TO_HOME_POINT.getErrorCode(),"飞机离原点太近了。"),
    RUNNING_MISSION(DJIMissionError. RUNNING_MISSION.getErrorCode(),"飞机正在执行任务"),
    REACH_FLIGHT_LIMITATION(DJIMissionError. REACH_FLIGHT_LIMITATION.getErrorCode(),"飞机已达到飞行极限"),
    AIRCRAFT_IN_NO_FLY_ZONE(DJIMissionError. AIRCRAFT_IN_NO_FLY_ZONE.getErrorCode(),"飞机处于禁飞区"),
    IN_NOVICE_MODE(DJIMissionError. IN_NOVICE_MODE.getErrorCode(),"飞机处于新手模式"),
    HOME_POINT_NOT_RECORDED(DJIMissionError. HOME_POINT_NOT_RECORDED.getErrorCode(),"飞机起飞点没有记录"),
    AIRCRAFT_GOING_HOME(DJIMissionError. AIRCRAFT_GOING_HOME.getErrorCode(),"飞机返航"),
    AIRCRAFT_LANDING(DJIMissionError. AIRCRAFT_LANDING.getErrorCode(),"飞机着陆"),
    AIRCRAFT_TAKING_OFF(DJIMissionError. AIRCRAFT_TAKING_OFF.getErrorCode(),"飞机正在起飞"),
    AIRCRAFT_ALTITUDE_TOO_LOW(DJIMissionError. AIRCRAFT_ALTITUDE_TOO_LOW.getErrorCode(),"飞机高度过低"),
    AIRCRAFT_ALTITUDE_TOO_HIGH(DJIMissionError. AIRCRAFT_ALTITUDE_TOO_HIGH.getErrorCode(),"飞机高度过高"),
    AIRCRAFT_NOT_IN_THE_AIR(DJIMissionError. AIRCRAFT_NOT_IN_THE_AIR.getErrorCode(),"飞机不在空中"),
    LOW_BATTERY(DJIMissionError. LOW_BATTERY.getErrorCode(),"电量低！"),
    GPS_SIGNAL_WEAK(DJIMissionError. GPS_SIGNAL_WEAK.getErrorCode(),"GPS信号弱"),
    MODE_ERROR(DJIMissionError. MODE_ERROR.getErrorCode(),"无法在当前模式下执行"),
    UNKNOWN(DJIMissionError. UNKNOWN.getErrorCode(),"未知错误"),
    USER_CANCEL_UPLOADING_MISSION(DJIMissionError. USER_CANCEL_UPLOADING_MISSION.getErrorCode(),"用户已取消上载任务。"),
    Z30_ONLY_SUPPORT_SPOTLIGHT_PRO(DJIMissionError. Z30_ONLY_SUPPORT_SPOTLIGHT_PRO.getErrorCode(),"Z30仅支持spotlight pro模式"),
    VISION_SENSOR_LOW_QUALITY(DJIMissionError. VISION_SENSOR_LOW_QUALITY.getErrorCode(),"视觉传感器质量低"),
    POINTING_AIRCRAFT_NOT_IN_THE_AIR(DJIMissionError. POINTING_AIRCRAFT_NOT_IN_THE_AIR.getErrorCode(),"飞机不在空中，请先起飞。"),
    WRONG_CMD(DJIMissionError. WRONG_CMD.getErrorCode(),"指令不正确。"),
    AIRCRAFT_STARTING_MOTOR(DJIMissionError. AIRCRAFT_STARTING_MOTOR.getErrorCode(),"飞机正在启动电机。"),
    WAYPOINT_IDLE_VELOCITY_INVALID(DJIMissionError. WAYPOINT_IDLE_VELOCITY_INVALID.getErrorCode(),"怠速无效。"),
    WAYPOINT_NOT_RUNNING(DJIMissionError. WAYPOINT_NOT_RUNNING.getErrorCode(),"航点任务未运行。"),
    WAYPOINT_REQUEST_IS_RUNNING(DJIMissionError. WAYPOINT_REQUEST_IS_RUNNING.getErrorCode(),"航点任务正在运行。"),
    WAYPOINT_UPLOAD_NOT_COMPLETE(DJIMissionError. WAYPOINT_UPLOAD_NOT_COMPLETE.getErrorCode(),"航路点上传未完成。"),
    WAYPOINT_MISSION_INFO_NOT_UPLOADED(DJIMissionError. WAYPOINT_MISSION_INFO_NOT_UPLOADED.getErrorCode(),"航路点任务的信息没有完全上传。"),
    WAYPOINT_ACTION_PARAMETER_INVALID(DJIMissionError. WAYPOINT_ACTION_PARAMETER_INVALID.getErrorCode(),"航路点动作的参数无效。"),
    WAYPOINT_DAMPING_CHECK_FAILED(DJIMissionError. WAYPOINT_DAMPING_CHECK_FAILED.getErrorCode(),"阻尼检测失败"),
    WAYPOINT_DISTANCE_TOO_LONG(DJIMissionError. WAYPOINT_DISTANCE_TOO_LONG.getErrorCode(),"航路点距离太长。航点间的有效距离小于2km"),
    WAYPOINT_DISTANCE_TOO_CLOSE(DJIMissionError. WAYPOINT_DISTANCE_TOO_CLOSE.getErrorCode(),"航路点距离太近。航点间的有效距离大于0.5m"),
    WAYPOINT_TOTAL_TRACE_TOO_LONG(DJIMissionError. WAYPOINT_TOTAL_TRACE_TOO_LONG.getErrorCode(),"总航路点任务距离太长。最大总距离是40公里。"),
    WAYPOINT_INDEX_OVER_RANGE(DJIMissionError. WAYPOINT_INDEX_OVER_RANGE.getErrorCode(),"航路点的索引超出范围。"),
    WAYPOINT_TRACE_TOO_LONG(DJIMissionError. WAYPOINT_TRACE_TOO_LONG.getErrorCode(),"航线太长。最大航路点轨迹为30公里。航路点跟踪是任务中各航路点之间所有距离的总和。"),
    MISSION_INFO_INVALID(DJIMissionError. MISSION_INFO_INVALID.getErrorCode(),"任务信息无效。"),
    MISSION_ACROSS_NO_FLY_ZONE(DJIMissionError. MISSION_ACROSS_NO_FLY_ZONE.getErrorCode(),"禁飞区！"),
    MISSION_CONDITION_NOT_SATISFIED(DJIMissionError. MISSION_CONDITION_NOT_SATISFIED.getErrorCode(),"任务的条件不满足！"),
    HIGH_PRIORITY_MISSION_EXECUTING(DJIMissionError. HIGH_PRIORITY_MISSION_EXECUTING.getErrorCode(),"一个更高优先级的任务正在执行！"),
    MULTI_MODE_IS_OFF(DJIMissionError. MULTI_MODE_IS_OFF.getErrorCode(),"多模式开关未打开！"),
    RTK_IS_NOT_READY(DJIMissionError. RTK_IS_NOT_READY.getErrorCode(),"RTK尚未准备好！"),
    MISSION_ESTIMATE_TIME_TOO_LONG(DJIMissionError. MISSION_ESTIMATE_TIME_TOO_LONG.getErrorCode(),"预估本次任务时间过长！"),
    MISSION_CONFLICT(DJIMissionError. MISSION_CONFLICT.getErrorCode(),"任务存在设置冲突！"),
    MISSION_NOT_EXIST(DJIMissionError. MISSION_NOT_EXIST.getErrorCode(),"任务不是已经初始化任务，任务不存在。"),
    MISSION_NOT_INITIALIZED(DJIMissionError. MISSION_NOT_INITIALIZED.getErrorCode(),"任务未初始化。"),
    IOC_WORKING(DJIMissionError. IOC_WORKING.getErrorCode(),"IOC模式正在运行。"),
    RC_MODE_ERROR(DJIMissionError. RC_MODE_ERROR.getErrorCode(),"遥控器模式错误。您应该将遥控器的模式选择栏置于F位置。"),
    DISTANCE_FROM_MISSION_TARGET_TOO_LONG(DJIMissionError. DISTANCE_FROM_MISSION_TARGET_TOO_LONG.getErrorCode(),"任务目标的距离过长"),
    NAVIGATION_MODE_NOT_SUPPORTED(DJIMissionError. NAVIGATION_MODE_NOT_SUPPORTED.getErrorCode(),"该设备不支持导航"),
    MISSION_RADIUS_OVER_LIMIT(DJIMissionError. MISSION_RADIUS_OVER_LIMIT.getErrorCode(),"任务的半径超过了可接受的限度"),
    MISSION_HEADING_MODE_INVALID(DJIMissionError. MISSION_HEADING_MODE_INVALID.getErrorCode(),"任务的航向模式无效"),
    MISSION_ENTRY_POINT_INVALID(DJIMissionError. MISSION_ENTRY_POINT_INVALID.getErrorCode(),"任务的入口点无效"),
    MISSION_SPEED_TOO_HIGH(DJIMissionError. MISSION_SPEED_TOO_HIGH.getErrorCode(),"任务中飞行速度设置过快"),
    MISSION_RADIUS_INVALID(DJIMissionError.MISSION_RADIUS_INVALID.getErrorCode(),"任务半径无效"),
    ALTITUDE_TOO_LOW(DJIMissionError.ALTITUDE_TOO_LOW.getErrorCode(),"飞行高度过低"),
    ALTITUDE_TOO_HIGH(DJIMissionError.ALTITUDE_TOO_HIGH.getErrorCode(),"飞行高度过高"),
    FOLLOW_ME_GIMBAL_PITCH_ERROR(DJIMissionError.FOLLOW_ME_GIMBAL_PITCH_ERROR.getErrorCode(),"云台初始化俯仰角度过大"),
    FOLLOW_ME_DISCONNECT_TIME_TOO_LONG(DJIMissionError.FOLLOW_ME_DISTANCE_TOO_LARGE.getErrorCode(),"任务终端超时"),
    FOLLOW_ME_DISTANCE_TOO_LARGE(DJIMissionError.FOLLOW_ME_DISTANCE_TOO_LARGE.getErrorCode(),"飞机与手机的距离太大（必须小于20000米）。"),
    HOME_POINT_MISSION_NOT_PAUSED(DJIMissionError.HOME_POINT_MISSION_NOT_PAUSED.getErrorCode(),"起飞点未暂停"),
    HOME_POINT_MISSION_PAUSED(DJIMissionError.HOME_POINT_MISSION_PAUSED.getErrorCode(),"起飞点已经暂停"),
    HOME_POINT_DIRECTION_UNKNOWN(DJIMissionError.HOME_POINT_DIRECTION_UNKNOWN.getErrorCode(),"起飞点方向未知。"),
    HOME_POINT_LOCATION_INVALID(DJIMissionError.HOME_POINT_LOCATION_INVALID.getErrorCode(),"起飞点经纬度无效。"),
    HOME_POINT_VALUE_INVALID(DJIMissionError.HOME_POINT_VALUE_INVALID.getErrorCode(),"起飞点数据无效。"),
    IOC_TYPE_UNKNOWN(DJIMissionError.IOC_TYPE_UNKNOWN.getErrorCode(),"IOC的类型未知。"),
    NAVIGATION_MODE_DISABLED(DJIMissionError.NAVIGATION_MODE_DISABLED.getErrorCode(),"导航未打开。"),
    KEY_LEVEL_LOW(DJIMissionError.KEY_LEVEL_LOW.getErrorCode(),"API密钥的权限级别不正确。"),
    UPLOADING_WAYPOINT(DJIMissionError.UPLOADING_WAYPOINT.getErrorCode(),"航路点正在上传。"),
    MAX_NUMBER_OF_WAYPOINTS_UPLOAD_LIMIT_REACHED(DJIMissionError.MAX_NUMBER_OF_WAYPOINTS_UPLOAD_LIMIT_REACHED.getErrorCode(),"航路点任务已达到最大点限制。"),
    NOT_AUTO_MODE(DJIMissionError.NOT_AUTO_MODE.getErrorCode(),"飞机不在自动模式。"),
    IS_FLYING(DJIMissionError.IS_FLYING.getErrorCode(),"飞机在飞行。"),
    TAKE_OFF(DJIMissionError.TAKE_OFF.getErrorCode(),"飞机正在起飞。"),
    MOTORS_DID_NOT_START(DJIMissionError.MOTORS_DID_NOT_START.getErrorCode(),"电机尚未启动"),
    GPS_NOT_READY(DJIMissionError.GPS_NOT_READY.getErrorCode(),"GPS没有准备好"),
    TIMEOUT(DJIMissionError.TIMEOUT.getErrorCode(),"任务超时"),
    NO_MISSION_RUNNING(DJIMissionError.NO_MISSION_RUNNING.getErrorCode(),"任务不存在"),
    FAILED(DJIMissionError.FAILED.getErrorCode(),"任务失败"),
    CANCELED(DJIMissionError.CANCELED.getErrorCode(),"任务已经取消"),
    BEGAN(DJIMissionError.BEGAN.getErrorCode(),"任务已经开始"),
    COMMON_UNSUPPORTED(DJIMissionError.COMMON_UNSUPPORTED.getErrorCode(),"不支持该功能"),
    COMMON_DISCONNECTED(DJIMissionError.COMMON_DISCONNECTED.getErrorCode(),"连接已断开");

    int code;
    String error;

    WayPointError(int code, String error) {
        this.code = code;
        this.error = error;
    }
    public static  String getError(int code) {

        for (WayPointError e : WayPointError.values()) {
            if (e.code == code) {
                return e.error;
            }
        }
        return "航线任务失败";

    }

}
